### ISSUE TITLE
Problems installing

### ISSUE THREAD

**Issue by jstansfield0** [kundajelab/3DChromatin_ReplicateQC#2]
I am trying to install 3DChromatin_ReplicateQC and I am having issues. I have all the requirements installed and when I try to run the installation script I get the following errors:

```

sudo ./install_3DChromatin_ReplicateQC.sh --pathtopython /home/John/anaconda2/bin/ --pathtor /home/John/R-3.4.0/bin/R --rlib /home/John/R-3.4.0/library/ --pathtobedtools /usr/bin/bedtools

Cloning into '/mnt/d/3DChromatin_ReplicateQC/software/genomedisco'...
remote: Counting objects: 1273, done.
remote: Total 1273 (delta 0), reused 0 (delta 0), pack-reused 1273
Receiving objects: 100% (1273/1273), 281.90 MiB | 2.78 MiB/s, done.
Resolving deltas: 100% (624/624), done.
Checking connectivity... done.

R version 3.4.0 (2017-04-21) -- "You Stupid Darkness"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> install.packages("pheatmap",repos="http://cran.rstudio.com/")
trying URL 'http://cran.rstudio.com/src/contrib/pheatmap_1.0.8.tar.gz'
Content type 'application/x-gzip' length 13759 bytes (13 KB)
==================================================
downloaded 13 KB

* installing *source* package ‘pheatmap’ ...
** package ‘pheatmap’ successfully unpacked and MD5 sums checked
** R
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (pheatmap)

The downloaded source packages are in
        ‘/tmp/RtmpWxevWx/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
>
>
Bioconductor version 3.5 (BiocInstaller 1.26.1), ?biocLite for help
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.5 (BiocInstaller 1.26.1), R 3.4.0 (2017-04-21).
Installing package(s) ‘hicrep’
trying URL 'https://bioconductor.org/packages/3.5/bioc/src/contrib/hicrep_1.0.0.tar.gz'
Content type 'application/x-gzip' length 193621 bytes (189 KB)
==================================================
downloaded 189 KB

* installing *source* package ‘hicrep’ ...
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (hicrep)

The downloaded source packages are in
        ‘/tmp/Rtmp90vL1z/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Old packages: 'boot', 'foreign', 'Matrix', 'mgcv'
Error in path.expand(new) : object 'new' not found
Calls: print ... .libPaths -> Sys.glob -> path.expand -> path.expand
Execution halted
Cloning into '/mnt/d/3DChromatin_ReplicateQC/software/HiC-spector'...
remote: Counting objects: 201, done.
remote: Total 201 (delta 0), reused 0 (delta 0), pack-reused 201
Receiving objects: 100% (201/201), 42.57 KiB | 0 bytes/s, done.
Resolving deltas: 100% (101/101), done.
Checking connectivity... done.
Cloning into '/mnt/d/3DChromatin_ReplicateQC/software/hifive'...
remote: Counting objects: 2191, done.
remote: Total 2191 (delta 0), reused 0 (delta 0), pack-reused 2191
Receiving objects: 100% (2191/2191), 2.86 MiB | 4.12 MiB/s, done.
Resolving deltas: 100% (1337/1337), done.
Checking connectivity... done.
./install_3DChromatin_ReplicateQC.sh: line 112: /home/John/anaconda2/python: No such file or directory
./install_3DChromatin_ReplicateQC.sh: line 113: /home/John/anaconda2/pip: No such file or directory
./install_3DChromatin_ReplicateQC.sh: line 114: /home/John/anaconda2/conda: No such file or directory
```

Do you know what the issue here is or how I can fix it?

**Comment by oursu** [comment]
I think the problem is that you set your python path to be `/home/John/anaconda2/` and it should be `/home/John/anaconda2/bin`. I will make this more clear in the README. Does that fix the problem?

**Comment by jstansfield0** [comment]
I did set the path to /home/John/anaconda2/bin/ in the option when I run the installation script.  What I entered to run it:

`sudo ./install_3DChromatin_ReplicateQC.sh --pathtopython /home/John/anaconda2/bin/ --pathtor /home/John/R-3.4.0/bin/R --rlib /home/John/R-3.4.0/library/ --pathtobedtools /usr/bin/bedtools`

**Comment by oursu** [comment]
My bad, I think it was a problem in the install script, where I was supposed to add the `bin` part. I've modified the install script to fix this. Can you please pull and try the install script again? Thanks.

**Comment by jstansfield0** [comment]
I tried again and now I am getting the following errors:

```

The downloaded source packages are in
        ‘/tmp/Rtmp7fuYwG/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Old packages: 'boot', 'foreign', 'Matrix', 'mgcv'
Error in path.expand(new) : object 'new' not found
Calls: print ... .libPaths -> Sys.glob -> path.expand -> path.expand
Execution halted
Cloning into '/mnt/d/3DChromatin_ReplicateQC/software/HiC-spector'...
remote: Counting objects: 201, done.
remote: Total 201 (delta 0), reused 0 (delta 0), pack-reused 201
Receiving objects: 100% (201/201), 42.57 KiB | 0 bytes/s, done.
Resolving deltas: 100% (101/101), done.
Checking connectivity... done.
Cloning into '/mnt/d/3DChromatin_ReplicateQC/software/hifive'...
remote: Counting objects: 2191, done.
remote: Total 2191 (delta 0), reused 0 (delta 0), pack-reused 2191
Receiving objects: 100% (2191/2191), 2.86 MiB | 4.14 MiB/s, done.
Resolving deltas: 100% (1337/1337), done.
Checking connectivity... done.
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/home/John/anaconda2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/John/anaconda2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/home/John/anaconda2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/John/anaconda2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/home/John/anaconda2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/John/anaconda2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/home/John/anaconda2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/John/anaconda2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/home/John/anaconda2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/John/anaconda2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/home/John/anaconda2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/John/anaconda2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
['hifive', 'hifive.commands', 'hifive.libraries']
Download error on https://pypi.python.org/simple/setuptools_cython/: unknown url type: https -- Some packages may not be found!
Download error on https://pypi.python.org/simple/setuptools-cython/: unknown url type: https -- Some packages may not be found!
Couldn't find index page for 'setuptools_cython' (maybe misspelled?)
Download error on https://pypi.python.org/simple/: unknown url type: https -- Some packages may not be found!
No local packages or working download links found for setuptools_cython
Traceback (most recent call last):
  File "setup.py", line 186, in <module>
    setup_package()
  File "setup.py", line 147, in setup_package
    setup(**metadata)
  File "/home/John/anaconda2/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/home/John/anaconda2/lib/python2.7/site-packages/setuptools/dist.py", line 335, in __init__
    self.fetch_build_eggs(attrs['setup_requires'])
  File "/home/John/anaconda2/lib/python2.7/site-packages/setuptools/dist.py", line 456, in fetch_build_eggs
    replace_conflicting=True,
  File "/home/John/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 863, in resolve
    replace_conflicting=replace_conflicting
  File "/home/John/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1141, in best_match
    return self.obtain(req, installer)
  File "/home/John/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1153, in obtain
    return installer(requirement)
  File "/home/John/anaconda2/lib/python2.7/site-packages/setuptools/dist.py", line 522, in fetch_build_egg
    return cmd.easy_install(req)
  File "/home/John/anaconda2/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 666, in easy_install
    raise DistutilsError(msg)
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('setuptools_cython')
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/home/John/anaconda2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/John/anaconda2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/home/John/anaconda2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/John/anaconda2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/home/John/anaconda2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/John/anaconda2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/home/John/anaconda2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/John/anaconda2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/home/John/anaconda2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/John/anaconda2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/home/John/anaconda2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/John/anaconda2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
Traceback (most recent call last):
  File "/home/John/anaconda2/bin/pip", line 7, in <module>
    from pip import main
  File "/home/John/anaconda2/lib/python2.7/site-packages/pip/__init__.py", line 21, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
  File "/home/John/anaconda2/lib/python2.7/site-packages/pip/_vendor/requests/__init__.py", line 62, in <module>
    from .packages.urllib3.exceptions import DependencyWarning
  File "/home/John/anaconda2/lib/python2.7/site-packages/pip/_vendor/requests/packages/__init__.py", line 29, in <module>
    import urllib3
  File "/home/John/anaconda2/lib/python2.7/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/home/John/anaconda2/lib/python2.7/site-packages/urllib3/connectionpool.py", line 29, in <module>
    from .connection import (
  File "/home/John/anaconda2/lib/python2.7/site-packages/urllib3/connection.py", line 39, in <module>
    from .util.ssl_ import (
  File "/home/John/anaconda2/lib/python2.7/site-packages/urllib3/util/__init__.py", line 6, in <module>
    from .ssl_ import (
  File "/home/John/anaconda2/lib/python2.7/site-packages/urllib3/util/ssl_.py", line 7, in <module>
    from hashlib import md5, sha1, sha256
ImportError: cannot import name md5
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/home/John/anaconda2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/John/anaconda2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/home/John/anaconda2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/John/anaconda2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/home/John/anaconda2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/John/anaconda2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/home/John/anaconda2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/John/anaconda2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/home/John/anaconda2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/John/anaconda2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/home/John/anaconda2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/John/anaconda2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
Traceback (most recent call last):
  File "/home/John/anaconda2/bin/conda", line 11, in <module>
    sys.exit(main())
  File "/home/John/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 182, in main
    return conda_exception_handler(_main, *args)
  File "/home/John/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 644, in conda_exception_handler
    return handle_exception(e)
  File "/home/John/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 634, in handle_exception
    print_unexpected_error_message(e)
  File "/home/John/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 596, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "/home/John/anaconda2/lib/python2.7/site-packages/conda/cli/main_info.py", line 162, in get_info_dict
    from ..connection import user_agent
  File "/home/John/anaconda2/lib/python2.7/site-packages/conda/connection.py", line 12, in <module>
    from requests import Session, __version__ as REQUESTS_VERSION
  File "/home/John/anaconda2/lib/python2.7/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/home/John/anaconda2/lib/python2.7/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/home/John/anaconda2/lib/python2.7/site-packages/urllib3/connectionpool.py", line 29, in <module>
    from .connection import (
  File "/home/John/anaconda2/lib/python2.7/site-packages/urllib3/connection.py", line 39, in <module>
    from .util.ssl_ import (
  File "/home/John/anaconda2/lib/python2.7/site-packages/urllib3/util/__init__.py", line 6, in <module>
    from .ssl_ import (
  File "/home/John/anaconda2/lib/python2.7/site-packages/urllib3/util/ssl_.py", line 7, in <module>
    from hashlib import md5, sha1, sha256
ImportError: cannot import name md5
```

**Comment by oursu** [comment]
I'm investigating why you are getting these errors.

1. I fixed the first one `Error in path.expand(new) : object 'new' not found`, so if you pull and retry, then that part should be fixed.
2. For the `ERROR:root:code for hash md5 was not found.`, I've been googling it and don't yet know how to fix it. This thread suggests that getting the latest anaconda might fix it (https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/GnXSLER003I), but I assume you already have the latest version (Anaconda2-5.0.0)? Also fwiw, a person in this thread (https://github.com/conda/conda/issues/1018) thought it might have something to do with using sudo, so you can try running the install command without `sudo` and see if that fixes it.

I'll get back to you once I figure out anything more.

**Comment by jstansfield0** [comment]
I tried without the sudo and with the newest push and am still getting the hash md5 errors.

**Comment by oursu** [comment]
Maybe try `sudo apt-get install openssl`?

**Comment by oursu** [comment]
or `/home/John/anaconda2/bin/conda install -c anaconda openssl`

**Comment by jstansfield0** [comment]
The problem was trying to install it using the Windows 10 ubuntu command line. It apparently does not support openssl. I was able to install using a virtual machine.

**Comment by oursu** [comment]
Sounds good. I will close this issue, but please let us know if you run into other problems or questions.
